on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        onefile: ['', '--onefile']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller msg.py ${{ matrix.onefile }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}${{ matrix.onefile }}-${{ github.head_ref }}
        path: dist/*
