name: CI

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        onefile: ['', '-onefile']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller msg${{ matrix.onefile }}.spec
    
    - id: commit
      uses: pr-mpt/actions-commit-hash@v1
    
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}${{ matrix.onefile }}-${{ steps.commit.outputs.short }}
        path: dist/*
